# Generated by Django 6.0 on 2025-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveBigIntegerField(null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('dataNascimento', models.DateField(null=True)),
            ],
        ),
    ]
